baseURL = "https://hly1204.github.io/myblog"
languageCode = 'zh-cn'
title = "hly1204's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "hly1204"
  lastmod = true
  url = "https://hly1204.github.io/myblog"
  favicon = "https://hly1204.github.io/myblog/images/icon.png"
  headerIcon = "https://hly1204.github.io/myblog/images/github-mark-white.png"
  avatar = "https://hly1204.github.io/myblog/images/icon.png"
  location = "Shanghai, China"

  github = "hly1204"
  twitter = "yeye39618806"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
